# docker-compose up --build --abort-on-container-exit
version: "3"

services:
  selenium:
    image: selenium/standalone-chrome:101.0
    container_name: selenium_server_works

  test:
    image: start_tests
    depends_on:
      - selenium








